# Generated by Django 5.1.1 on 2026-02-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total_equipment", models.IntegerField()),
                ("average_flowrate", models.FloatField()),
                ("average_pressure", models.FloatField()),
                ("average_temperature", models.FloatField()),
                ("type_distribution", models.JSONField()),
            ],
        ),
    ]
